# Archivo: .streamlit/config.toml

[theme]

# Color primario (botones, sliders, widgets) - Un azul vibrante
primaryColor="#00A0FF"

# Color de fondo principal - Un azul muy oscuro (casi negro)
backgroundColor="#EDCC9A"

# Color de fondo para elementos como la barra lateral y selectores
secondaryBackgroundColor="#C2924F"

# Color del texto principal (sobre el fondo oscuro)
textColor="#402F20"

# Color de las fuentes (ej. Garamond, serif)
font="Quicksand"
