# Archivo: .streamlit/config.toml
[theme]

# Color primario (botones, sliders, widgets) - Un azul profesional
primaryColor="#0068C9"

# Color de fondo principal
backgroundColor="#FFFFFF"

# Color de fondo para elementos como la barra lateral
secondaryBackgroundColor="#F0F5F9"

# Color del texto principal
textColor="#31333F"

# Fuente
font="sansÂ serif"
