# Archivo: .streamlit/config.toml
[theme]

# Color primario (botones, sliders, widgets) - Un amarillo/ámbar vibrante
primaryColor="#000000"

# Color de fondo principal - Negro
backgroundColor="#0E1117"

# Color de fondo para elementos como la barra lateral
secondaryBackgroundColor="#1C2833"

# Color del texto principal
textColor="#FFFFFF"

# Fuente
font="sans serif"
