# Archivo: .streamlit/config.toml
[theme]

# Color primario (botones, sliders, widgets) - Un verde menta
primaryColor="#1ABC9C"

# Color de fondo principal - Un gris/verde muy oscuro
backgroundColor="#1F2937"

# Color de fondo para elementos como la barra lateral
secondaryBackgroundColor="#37475A"

# Color del texto principal
textColor="#FFFFFF"

# Fuente
font="sansÂ serif"
