# Archivo: .streamlit/config.toml
[theme]
primaryColor = "#2E8B57"              # Verde bosque
backgroundColor = "#F5F7F2"           # Fondo suave tipo papel
secondaryBackgroundColor = "#DDE6D5"  # Verde claro de apoyo
textColor = "#1C1C1C"                 # Gris oscuro
font = "Poppins"                      # Fuente elegante y amigable
