# Archivo: .streamlit/config.toml
[theme]

# Color primario (botones, sliders, widgets) - Un amarillo/Ã¡mbar vibrante
primaryColor="#FAAF5A"

# Color de fondo principal - Negro
backgroundColor="#000000"

# Color de fondo para elementos como la barra lateral
secondaryBackgroundColor="#FAAF5A"

# Color del texto principal
textColor="#FFFFFF"

# Fuente
font="Quicksand"
